# Generated by Django 5.0.2 on 2024-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_libro', models.FileField(upload_to='archivos/', verbose_name='Archivo de libro cientifico con Arbitraje')),
            ],
        ),
        migrations.CreateModel(
            name='a10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_carta_impl', models.FileField(upload_to='archivos/', verbose_name='Implementación tecnológica.')),
            ],
        ),
        migrations.CreateModel(
            name='a11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_art_div_cien', models.FileField(upload_to='archivos/', verbose_name='Archivo publicación de artículo o nota científica en revista arbitrada de divulgación científica obtecnológica.')),
            ],
        ),
        migrations.CreateModel(
            name='a12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_proy_inv_cien', models.FileField(upload_to='archivos/', verbose_name='Archivo participación en proyectos de investigación científica, desarrollo tecnológico e innovación con financiamiento externo obtenido mediante convocatoria.')),
            ],
        ),
        migrations.CreateModel(
            name='a13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_inv_sni', models.FileField(upload_to='archivos/', verbose_name='Archivo investigador perteneciente al SNI.')),
            ],
        ),
        migrations.CreateModel(
            name='a14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_edit_comp_coor', models.FileField(upload_to='archivos/', verbose_name='Archivo de editor, compilador o coordinador de libro colectivo')),
            ],
        ),
        migrations.CreateModel(
            name='a2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_patente', models.FileField(upload_to='archivos/', verbose_name='Archivo de Solicitud de Patente')),
            ],
        ),
        migrations.CreateModel(
            name='a3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_tit_patente', models.FileField(upload_to='archivos/', verbose_name='Archivo de obtención del título de Derechos de Patente')),
            ],
        ),
        migrations.CreateModel(
            name='a4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_tram_obtentor', models.FileField(upload_to='archivos/', verbose_name='Archivo de trámite de solicitud de derecho de obtentor')),
            ],
        ),
        migrations.CreateModel(
            name='a5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_dere_obtentor', models.FileField(upload_to='archivos/', verbose_name='Archivo obtención de derecho de obtentor')),
            ],
        ),
        migrations.CreateModel(
            name='a6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_soft_autor', models.FileField(upload_to='archivos/', verbose_name='Archivo desarrollo de software con derechos de autor')),
            ],
        ),
        migrations.CreateModel(
            name='a7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_art_rev_indx', models.FileField(upload_to='archivos/', verbose_name='Archivo publicación de artículo o nota científica en revista indexada')),
            ],
        ),
        migrations.CreateModel(
            name='a8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_art_rev_arb', models.FileField(upload_to='archivos/', verbose_name='Archivo publicación de artículo científico o nota científica en revista arbitrada.')),
            ],
        ),
        migrations.CreateModel(
            name='a9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_libr_cien_arb', models.FileField(upload_to='archivos/', verbose_name='Autoría o Coautoría de capítulo de libro científico con arbitraje.')),
            ],
        ),
        migrations.CreateModel(
            name='aa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_libro', models.FileField(upload_to='archivos/', verbose_name='Archivo de libro cientifico con Arbitraje')),
            ],
        ),
        migrations.CreateModel(
            name='b1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100, verbose_name='Nombre de la especialidad')),
                ('cedula_profesional', models.CharField(default=' ', max_length=100, verbose_name='Cédula profesional')),
                ('fecha', models.TextField(null=True, verbose_name='Fecha de obtención')),
                ('titulo', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Titulo')),
                ('cedula', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Cédula')),
                ('carta_conacyt', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Carta conacyt')),
            ],
        ),
        migrations.CreateModel(
            name='b10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_dir_tes_esp', models.FileField(upload_to='archivos/', verbose_name='Archivo de trabajo de dirección de trabajos de tesis de especialidad médica de alumnos graduados y/o titulados.')),
            ],
        ),
        migrations.CreateModel(
            name='b11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_dir_tes_maes', models.FileField(upload_to='archivos/', verbose_name='Archivo de trabajo de dirección de trabajos de tesis de maestría de doctorado de alumnos graduados y/o titulados.')),
            ],
        ),
        migrations.CreateModel(
            name='b12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_dir_tes_doc', models.FileField(upload_to='archivos/', verbose_name='Archivo de trabajo de dirección de trabajos de tesis de alumnos graduados y/o titulados.')),
            ],
        ),
        migrations.CreateModel(
            name='b13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_ases_alum', models.FileField(upload_to='archivos/', verbose_name='Archivo de trabajo de asesoría de alumno de licenciatura, especialidad, maestría o doctorado en estancia de investigación')),
            ],
        ),
        migrations.CreateModel(
            name='b14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('pon_cong_simp_inter', models.FileField(upload_to='archivos/', verbose_name='Archivo de ponencias en congresos o simposios científicos internacionales')),
            ],
        ),
        migrations.CreateModel(
            name='b15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('pon_cong_simp_nac', models.FileField(upload_to='archivos/', verbose_name='Archivo de ponencias en congresos o simposios científicos nacionales')),
            ],
        ),
        migrations.CreateModel(
            name='b16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('pres_cart_simp_inter', models.FileField(upload_to='archivos/', verbose_name='Archivo de presentación de carteles en congresos o simposios científicos internacionales')),
            ],
        ),
        migrations.CreateModel(
            name='b17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('pres_cart_simp_nac', models.FileField(upload_to='archivos/', verbose_name='Archivo de presentación de carteles en congresos o simposios científicos nacionales')),
            ],
        ),
        migrations.CreateModel(
            name='b18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_estancia', models.FileField(upload_to='archivos/', verbose_name='Archivo de Estancia de Investigación')),
            ],
        ),
        migrations.CreateModel(
            name='b19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_asignaturas', models.FileField(upload_to='archivos/', verbose_name='Archivo de Asignaturas con créditos impartidas')),
            ],
        ),
        migrations.CreateModel(
            name='b2',
            fields=[
                ('idmae', models.AutoField(primary_key=True, serialize=False)),
                ('idinv', models.CharField(max_length=20, verbose_name='Id Investigador')),
                ('nombre_maestría', models.CharField(max_length=100, verbose_name='Nombre de Maestría')),
                ('cedula_profesional', models.CharField(max_length=20, verbose_name='Cedula Profesional')),
                ('fecha_obtención', models.TextField(null=True, verbose_name='Fecha Obtención de Grado')),
                ('archivo_titulo', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Archivo Titulo')),
                ('archivo_cedula', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Archivo Cedula')),
                ('archivo_carta_recono_conacyt', models.FileField(null=True, upload_to='media/archivos/', verbose_name='Archivo Carta')),
            ],
        ),
        migrations.CreateModel(
            name='b20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_proyecto', models.FileField(upload_to='media/archivos/', verbose_name='Archivo de registro del proyecto en la institución')),
            ],
        ),
        migrations.CreateModel(
            name='b21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_pub_art_rev', models.FileField(upload_to='media/archivos/', verbose_name='Archivo publicación de artículo en revista no arbitrada de divulgación científica o tecnológica')),
            ],
        ),
        migrations.CreateModel(
            name='b22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_part_event', models.FileField(upload_to='media/archivos/', verbose_name='Archivo departicipación en eventos de divulgación científica')),
            ],
        ),
        migrations.CreateModel(
            name='b23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_ev_trab_inv', models.FileField(upload_to='media/archivos/', verbose_name='Archivo de evaluación de trabajos de Investigación o Proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='b3',
            fields=[
                ('IdDoc', models.AutoField(primary_key=True, serialize=False)),
                ('idInv', models.IntegerField(verbose_name='Id Investigador')),
                ('nombre_doctorado', models.CharField(max_length=100, verbose_name='Nombre del Doctorado')),
                ('cedula_profesional', models.CharField(max_length=20, verbose_name='Cedula Profesional')),
                ('fecha_obtención', models.TextField(null=True, verbose_name='Fecha Obtención de Grado')),
                ('archivo_titulo', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Titulo')),
                ('archivo_cedula', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Cedula')),
                ('archivo_carta_recono_conacyt', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Carta')),
            ],
        ),
        migrations.CreateModel(
            name='b4',
            fields=[
                ('IdMae', models.AutoField(primary_key=True, serialize=False)),
                ('idInv', models.IntegerField(verbose_name='Id Investigador')),
                ('nombre_maestria', models.TextField(verbose_name='Nombre de la Especialidad')),
                ('nombre_inst_edu', models.TextField(verbose_name='Nombre de la Institución Educativa')),
                ('pais', models.TextField(verbose_name='País')),
                ('fecha_obtención', models.TextField(verbose_name='Fecha de Obtención')),
                ('archivo_titulo', models.FileField(upload_to='archivos/', verbose_name='Archivo del Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='b5',
            fields=[
                ('IdDoc', models.AutoField(primary_key=True, serialize=False)),
                ('idInv', models.IntegerField(verbose_name='Id Investigador')),
                ('nombre_doctorado', models.TextField(max_length=100, verbose_name='Nombre de la Especialidad')),
                ('nombre_inst_edu', models.TextField(verbose_name='Nombre de la Institución Educativa')),
                ('pais', models.TextField(verbose_name='País')),
                ('fecha_obtención', models.TextField(verbose_name='Fecha de Obtención')),
                ('archivo_titulo', models.FileField(upload_to='archivos/', verbose_name='Archivo del Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='b6',
            fields=[
                ('idEsp', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Especialidad')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('nom_especialidad', models.TextField(verbose_name='Nombre de la especialidad')),
                ('ced_prof', models.TextField(verbose_name='Cedula Profesional')),
                ('fech_obt', models.TextField(verbose_name='Fecha')),
                ('arch_titulo', models.FileField(upload_to='archivos/', verbose_name='Archivo Titulo')),
                ('arch_cedula', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Cedula Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='b7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMae', models.IntegerField(default='1', verbose_name='Id de Maestria')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('nom_maes', models.TextField(verbose_name='Nombre de la Maestria')),
                ('ced_prof', models.TextField(verbose_name='Cedula Profesional')),
                ('fech_obt', models.TextField(verbose_name='Fecha')),
                ('arch_titulo', models.FileField(upload_to='archivos/', verbose_name='Archivo Titulo')),
                ('arch_cedula', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Cedula Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='b8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDoc', models.IntegerField(default='1', verbose_name='Id de Maestria')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('nom_doc', models.TextField(verbose_name='Nombre del Doctorado')),
                ('ced_prof', models.TextField(verbose_name='Cedula Profesional')),
                ('fech_obt', models.TextField(verbose_name='Fecha')),
                ('arch_titulo', models.FileField(upload_to='archivos/', verbose_name='Archivo Titulo')),
                ('arch_cedula', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo Cedula Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='b9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInv', models.IntegerField(default='1', verbose_name='Id del Investigador')),
                ('arch_dir_tes_lic', models.FileField(upload_to='archivos/', verbose_name='Archivo de trabajo de dirección de trabajos de tesis de licenciatura de alumnos graduados y/o titulados.')),
            ],
        ),
    ]
