# Generated by Django 5.0.2 on 2024-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_calificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('investigador', 'Investigador'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='sin_asignar', max_length=20),
        ),
    ]
