# Generated by Django 5.0.3 on 2024-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_delete_calificacion_alter_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(blank=True, max_length=20, verbose_name='rol'),
        ),
    ]
