# Generated by Django 5.0.3 on 2024-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(blank=True, choices=[('sin_asignar', 'Sin asignar'), ('investigador', 'Investigador'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], max_length=20, verbose_name='rol'),
        ),
    ]
