# Generated by Django 5.0.3 on 2024-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('investigador', 'Investigador'), ('evaluador', 'Evaluador'), ('admin', 'Administrador')], default='sin_asignar', max_length=20, verbose_name='rol'),
        ),
    ]
